version: '3.7'
services:
  gerocuidado-forum-api:
    image: node:18.13.0
    container_name: gerocuidado-forum-api
    volumes:
      - .:/home/node/app
    entrypoint: bash /home/node/app/.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '3002:3002'
      - '7002:9002'
    depends_on:
      - gerocuidado-forum-db
    networks:
      - gerocuidado-forum-net

  gerocuidado-forum-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-forum-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5002:5002'
    networks:
      - gerocuidado-forum-net

networks:
  gerocuidado-forum-net:
    driver: bridge
