version: '3.7'
services:
  gerocuidado-forum-api-prod:
    image: gerocuidadodev/gerocuidado-forum-api:latest
    container_name: gerocuidado-forum-api-prod
    environment:
      - DB_HOST=gerocuidado-forum-db
      - DB_USERNAME=postgres
      - DB_PASS=postgres
      - DB_DATABASE=gerocuidado-forum-db
      - DB_PORT=5002
      - AUTH_HOST=gerocuidado-usuario-api-prod
      - AUTH_PORT=4001
    ports:
      - '3002:3002'
    depends_on:
      - gerocuidado-forum-db
    networks:
      - gerocuidado-forum-net
      - gerocuidado-apis-net

  gerocuidado-forum-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    container_name: gerocuidado-forum-db
    volumes:
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-forum-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5002:5002'
    networks:
      - gerocuidado-forum-net

networks:
  gerocuidado-forum-net:
    driver: bridge
  gerocuidado-apis-net:
    name: gerocuidado-apis-net
    external: true
